### ISSUE TITLE
Faire une proposition d'UX différente pour la sélection des types d'action

### ISSUE THREAD

**Issue by rbailly** [philharmoniedeparis/carte_DG#11]
On est face à un paradoxe qui va être encore plus problématique lorsque l'on va pouvoir sélectionner plusieurs types d'action:
- Quand on arrive sur la carte et que tout est visible, aucune action n'est "sélectionnée"
- Quand on "sélectionne" un type d'action, en fait on "dé-selectionne les autres", mais ils ne changent pas d'état
- > On a donc un état qui correspond à la fois à l'action de sélection et à l'action de déselection.

Je ne vois pas d'autre moyen que de reprendre le principe des cases à cocher (avec sélection "multiple"), mais il faut cependant garder le moyen de faire comprendre le principe des couleurs dès le départ.

**Comment by ChristopheLeonardi** [comment]
La mise en place de checkboxs sur les filtres ont permis de mieux spécifier les états des entrées du filtre. Leurs états est plus visible, cependant j'ai du abandonné le fond coloré lorsque les filtres sont sélectionnés pour ne pas avoir un côté arc-en-ciel avec toutes les couleurs présentes d'emblée sur les filtres.

Si elles sont trop discrètes je travaillerai à une accentuation sur les labels.
