### ISSUE TITLE
Bouton reset de la carte ne fonctionne plus

### ISSUE THREAD

**Issue by rbailly** [philharmoniedeparis/carte_DG#19]
Un clic sur le bouton reset envoie "resetmap" dans la recherche et n'a aucun effet.

https://drop.philharmoniedeparis.fr/carte/

Chose étrange, le bug n'est pas reproductible avec ?private=true dans l'URL

**Comment by ChristopheLeonardi** [comment]
Le bug est résolu, c'est uploadé sur mon site et github
Cela venait de l'absence du filtre de statut qui faisait buggé le filtre de recherche.
Le reset est envoyé via le mot clé resetMap dans l'input du champ texte (stratégie un peu hack mais sinon j'avais des conflits dans les destruction et création de cartes lors des recherches et réinitialisation).
