### ISSUE TITLE
Proposition de mise en page pour le haut du cartel

### ISSUE THREAD

**Issue by rbailly** [philharmoniedeparis/carte_DG#5]
Première ligne : Toujours remettre le rond de couleur, avec ou sans icône de prospect PUIS type d'action PUIS " - Prospect" s'il s'agit d'un prospect

Ne pas indiquer la région

Retour à la ligne entre Ville et Pays

**Comment by ChristopheLeonardi** [comment]
Mise en page changée

**Comment by rbailly** [comment]
![Capture d'écran 2023-10-26 171823](https://github.com/philharmoniedeparis/carte_DG/assets/10194536/d9dcd0c8-ac38-4766-a511-96a406dceae5)
![Capture d'écran 2023-10-26 171853](https://github.com/philharmoniedeparis/carte_DG/assets/10194536/4c983f11-d260-47d2-be62-f333e65ebf70)
![Capture d'écran 2023-10-26 171949](https://github.com/philharmoniedeparis/carte_DG/assets/10194536/e9a6fdcc-409b-4801-9fd7-5d4a61602d01)
![Capture d'écran 2023-10-26 172030](https://github.com/philharmoniedeparis/carte_DG/assets/10194536/4037ef47-ce2f-4b0d-9fc4-6ae466534f41)

**Comment by rbailly** [comment]
Bon, visiblement ma proposition ne fonctionne pas bien. . . Je propose d'en discuter ensemble de vive voix
