### ISSUE TITLE
Affichage des types d'action dans un ordre donné

### ISSUE THREAD

**Issue by rbailly** [philharmoniedeparis/carte_DG#6]
Nous devons maitriser l'ordre d'affichage des actions dans les filtres sur la carte. 

2 solutions : 

- On laisse comme ça et on change l'ordre dans des lignes dans le fichier config. En effet, si je regarde les données, elles sont "rangées" dans le même ordre. => Un peu "risqué"
- On ajoute une donnée transmise dans le premier "bloc", pilotée ou non par une nouvelle colonne "order" dans le fichier de config.

**Comment by ddenocq** [comment]
La première solution est peut-être "suffisante", c'est elle qui définit aussi l'odre dans le premier bloc.
Peu de personnes sont succeptibles de modifier le fichier config.

**Comment by rbailly** [comment]
Ok, on laisse tel quel!
