### ISSUE TITLE
Comportement erratique lors de la sélection d'un type d'action.

### ISSUE THREAD

**Issue by rbailly** [philharmoniedeparis/carte_DG#9]
pde possède 4 points
Si on sélectionne "Philharmonie des enfants", tous ne s'affichent pas. J'ai eu une fois seulement 2 points, puis seulement 3 points ( le point d'Argenteuil ne s'affiche pas)
Par contre si on est en mode "toutes les actions" et qu'on zoome sur Argenteuil, on le trouve

**Comment by ChristopheLeonardi** [comment]
réglé
